### ISSUE TITLE
Using clreduce to replicate PLDI'15 experiments

### ISSUE THREAD

**Issue by ChrisCummins** [mpflanzer/clreduce#2]
Hi,

I'm trying to replicate the experiments of the "Many-Core Compiler Fuzzing" paper [1], specifically, generating a table of wrong-code, build-failure, crash, and timeout results for CSmith programs on a handful of OpenCL configurations:

<img width="730" alt="screen shot 2017-07-09 at 07 54 50" src="https://user-images.githubusercontent.com/1636663/27991849-eca57606-647b-11e7-9794-890a77da2ab7.png">

From what I understand, this should be possible by grepping the output of the `reduction_helper` script:

```
$ python3 ./scripts/reduction_helper.py \
    --generate 1000 \
    --modes barriers atomics atomic_reductions vectors inter_thread_comm \
    --preprocess \
    --reduce-work-sizes-unchecked \
    --output $OUTPUT_DIR \
    --test wrong-code-bug \
    --check \
    --reduce \
    -n 4 \
    --verbose
CLProg_0.cl -> generated -> preprocessed -> work sizes reduced -> failure (static)
CLProg_1.cl -> generated -> preprocessed -> work sizes reduced -> timeout (oclgrind
CLProg_2.cl -> generated -> preprocessed -> work sizes reduced -> same output
...
CLProg_110.cl -> generated -> preprocessed -> work sizes reduced -> different output -> reduced -> done
```

Where **w**rong-code is `different output`, **b**uild **f**ailure is `failure (static)`, **c**rash is `failure ({optimised,unoptimised,oracle})`, and ✓✓✓"passes" are `same output`.

Can I just check that I've interpreted the output of `reduction_helper` correctly?

Cheers,
Chris

[1] Lidbury, C., Lascu, A., Chong, N., & Donaldson, A. (2015). Many-Core Compiler Fuzzing. In PLDI.

**Comment by mpflanzer** [comment]
I think it's not possible to find a perfect 1:1 mapping between the outputs of the script and the table (I wrote the script after they published this paper).

- "different output" is definite equivalent to wrong-code.
- "same output" is passes

The problem is with build failure and crash. IIRC, build failure which means that the device (e.g. GPU) failed to build the test case whereas crash means the device failed to properly execute the test case. The script does not distinguish between those two scenarios. They would both be reported as "failure {optimised, unoptimised}".

- "failure {static, oracle}" means the test case is invalid with regard to some criterion. (E.g. static analysis showed use of undefined values or dynamic analysis might have detected a race condition).

It should no be to difficult to extend the script to treat build failures and crashed separately. I think cl_launcher will return a different return code in both situations which could be checked.

**Comment by ChrisCummins** [comment]
Ah okay, thanks for clearing that up!
